
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.23"

[[constraint]]
  name = "github.com/function61/eventhorizon"
  version = "0.2.0"

[[constraint]]
  name = "github.com/hashicorp/hcl"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true
